import { NextApiRequest, NextApiResponse } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "./auth/[...nextauth]";
const harryPotterJokes: string[] = [
  "Why did Hermione open a bakery? She kneaded the dough for her success!",
  "Why did Hermione take up a job at the Ministry of Magic? She loves 'spell'-ing out new laws!",
  "What did Hermione say when Ron asked her to dance? 'You must be joking!'",
  "Why did Hermione bring a ladder to Hogwarts? To help her 'reach' the top of her class!",
  "Why did Hermione become a therapist? She was an expert at 'removing' people's problems!",
  "What's Hermione's favorite kind of exercise? Granger-robics!",
  "Why did Hermione become the editor of the Daily Prophet? She knew how to 'spell' the news correctly!",
  "Why was Hermione the best at magic chess? She knew the importance of the 'Hermione' maneuver!",
  "Why did Hermione start a knitting club at Hogwarts? She wanted to 'knit' Gryffindor scarves for everyone!",
  "Why did Hermione create her own magical creatures? She wanted to prove she could be 'Granger'-ous too!",
  "What do you call it when Hermione loses her temper? A 'Hermi-outburst'!",
  "Why did Hermione start a study group for Defense Against the Dark Arts? To help others 'spell' better!",
  "What's Hermione's favorite subject at Hogwarts? 'Wand'-ology!",
  "Why did Hermione become an author? She knew the power of 'spell'-ing out a good story!",
  "Why did Hermione become a detective? She was always 'Granger'-ous in solving mysteries!",
  "What's Hermione's favorite drink at The Three Broomsticks? 'Grainger'-ale!",
  "Why did Hermione start a gardening club at Hogwarts? She loved 'grow'-ing her own magical herbs!",
  "What did Hermione say when she received the highest marks in Potions class? 'It's just a little 'brew'-haha!'",
  "Why did Hermione become a Quidditch coach? She knew how to 'Granger'-ly train the best players!",
  "What's Hermione's favorite song? 'Don't Stop 'til You Granger-Enough!'",
  "Why did Hermione go to the Muggle world? She wanted to learn more about 'physics'-matics!",
  "What do you call it when Hermione starts dancing spontaneously? A 'Granger'-tainment show!",
  "Why did Hermione become a musician? She mastered the 'Hermione'-ca!",
  "Why did Hermione go to the beach? To show off her 'Granger'-ie swimsuit!",
  "What's Hermione's favorite type of puzzle? 'Granger'-saw puzzles!",
  "Why did Harry Potter go to the bank? To check his 'galleon'-s!",
  "What's Harry Potter's favorite way to go into a room? Through the 'Sirius'-ly locked door!",
  "Why did Harry Potter get a ticket while riding his broom? He was flying above the 'speed limit-us!'",
  "Why did Harry Potter become a singer? He had the 'voice'-tory in him!",
  "What do you call it when Harry Potter falls down a flight of stairs? A 'Harry'-rible accident!",

  // Additional jokes with Hermione focus
  "Why did Hermione start her own fashion line? Her outfits were always 'Granger'-geous!",
  "What's Hermione's favorite dessert? 'Granger'-ine pie with a side of 'Granger'-ines!",
  "Why did Hermione start a magical book club? She wanted to 'spell'-bound her fellow readers!",
  "What's Hermione's favorite spell? 'Hermione'-ous Revelio!",
  "Why did Hermione become a stand-up comedian? She had a 'Hermione'-ac sense of humor!",
  "Why did Hermione start a magical research institute? To 'Granger'-deep into the mysteries of the wizarding world!",
  "What do you call it when Hermione is in charge of the party decorations? 'Granger'-fest!",
  "Why did Hermione become a potion brewer? She knew the 'Granger'-dients for success!",
  "What's Hermione's favorite magical creature? 'Granger'-iffins!",
  "Why did Hermione start a tutoring service? She wanted to help others 'Granger'-stand difficult subjects!",
  "What do you call it when Hermione gets excited about magic? A 'Hermione'-a!",
  "Why did Hermione start a magical art class? She loved to 'Granger'-paint masterpieces!",
  "What's Hermione's favorite sport? 'Granger'-tennis!",
  "Why did Hermione start a charity for house-elves? She believed in 'Granger'-justice for all magical beings!",
  "What do you call it when Hermione is preparing for exams? 'Granger'-vation mode!",
  "Why did Hermione start a magical music band? She was a 'Granger'-tastic singer!",
  "What's Hermione's favorite type of joke? 'Granger'-knock jokes!",
  "Why did Hermione become a magical archaeologist? She loved to 'Granger'-vestigate ancient ruins!",
  "What do you call it when Hermione is having a magical meal? 'Granger'-nomics!",
  "Why did Hermione start a magical pet adoption center? She believed in 'Granger'-ting homes for all creatures!",
  "What's Hermione's favorite magical drink? 'Granger'-beer!",
  "Why did Hermione become a magical architect? She knew how to 'Granger'-design enchanting buildings!",
  "What do you call it when Hermione is using her time-turner? 'Granger'-back in time!",
  "Why did Hermione start a magical technology club? She loved to 'Granger'-hack the latest gadgets!",
  "What's Hermione's favorite magical board game? 'Granger'-opoly!",
  "Why did Hermione become a magical therapist? She knew how to 'Granger'-stand people's emotions!",
  "What do you call it when Hermione is organizing a party? 'Granger'-ment planning!",
  "Why did Hermione start a magical dance academy? She could 'Granger'-gically move to any beat!",
  "What's Hermione's favorite magical snack? 'Granger'-nola bars!",
  "Why did Hermione become a magical scientist? She wanted to 'Granger'-periment with new spells!",
  "What do you call it when Hermione is on a broomstick? 'Granger'-riding!",
  "Why did Hermione start a magical comedy club? Her jokes were always 'Granger'-larity!",
  "What's Hermione's favorite magical color? 'Granger'-ine!",
  "Why did Hermione become a magical detective? She could 'Granger'-vestigate any mystery!",
  "What do you call it when Hermione is doing homework? 'Granger'-ding her knowledge!",
  "Why did Hermione start a magical bakery? Her pastries were always 'Granger'-licious!",
  "What's Hermione's favorite magical candy? 'Granger'-drops!",
  "Why did Hermione open a bakery? She kneaded the dough for her success!",
  "Why did Hermione take up a job at the Ministry of Magic? She loves 'spell'-ing out new laws!",
  "What did Hermione say when Ron asked her to dance? 'You must be joking!'",
  "Why did Hermione bring a ladder to Hogwarts? To help her 'reach' the top of her class!",
  "Why did Hermione become a therapist? She was an expert at 'removing' people's problems!",
  "What's Hermione's favorite kind of exercise? Granger-robics!",
  "Why did Hermione become the editor of the Daily Prophet? She knew how to 'spell' the news correctly!",
  "Why was Hermione the best at magic chess? She knew the importance of the 'Hermione' maneuver!",
  "Why did Hermione start a knitting club at Hogwarts? She wanted to 'knit' Gryffindor scarves for everyone!",
  "Why did Hermione create her own magical creatures? She wanted to prove she could be 'Hermione'-ous too!",
  "What do you call it when Hermione loses her temper? A 'Hermi-outburst'!",
  "Why did Hermione start a study group for Defense Against the Dark Arts? To help others 'spell' better!",
  "What's Hermione's favorite subject at Hogwarts? 'Wand'-ology!",
  "Why did Hermione become an author? She knew the power of 'spell'-ing out a good story!",
  "Why did Hermione become a detective? She was always 'Hermione'-ous in solving mysteries!",
  "What's Hermione's favorite drink at The Three Broomsticks? 'Grainger'-ale!",
  "Why did Hermione start a gardening club at Hogwarts? She loved 'grow'-ing her own magical herbs!",
  "What did Hermione say when she received the highest marks in Potions class? 'It's just a little 'brew'-haha!'",
  "Why did Hermione become a Quidditch coach? She knew how to 'Hermione'-ly train the best players!",
  "What's Hermione's favorite song? 'Don't Stop 'til You Granger-Enough!'",
  "Why did Hermione go to the Muggle world? She wanted to learn more about 'physics'-matics!",
  "What do you call it when Hermione starts dancing spontaneously? A 'Granger'-tainment show!",
  "Why did Hermione become a musician? She mastered the 'Hermione'-ca!",
  "Why did Hermione go to the beach? To show off her 'Hermione'-ie swimsuit!",
  "What's Hermione's favorite type of puzzle? 'Hermione'-saw puzzles!",
  "Why did Harry Potter go to the bank? To check his 'galleon'-s!",
  "What's Harry Potter's favorite way to go into a room? Through the 'Sirius'-ly locked door!",
  "Why did Harry Potter get a ticket while riding his broom? He was flying above the 'speed limit-us!'",
  "Why did Harry Potter become a singer? He had the 'voice'-tory in him!",
  "What do you call it when Harry Potter falls down a flight of stairs? A 'Harry'-rible accident!",
  "Why did Hermione become a magical archaeologist? She loved 'dig'-ging into history!",
  "What's Hermione's favorite mode of transportation? 'Hermione'-porting!",
  "Why did Hermione start a magical escape room? She knew how to 'Hermione'-d tricky puzzles!",
  "Why did Hermione become a magical painter? Her artwork was always 'Hermione'-sional!",
  "What do you call it when Hermione is flying on her broomstick? 'Hermione'-ing through the sky!",
  "Why did Hermione start a magical language school? She knew how to 'Hermione'-strate eloquence!",
  "What's Hermione's favorite magical creature? 'Hermione'-corns!",
  "Why did Hermione become a magical chef? She cooked with 'Hermione'-ation!",
  "What do you call it when Hermione is in a hurry? A 'Hermione'-rush!",
  "Why did Hermione start a magical theater troupe? She could 'Hermione'-volve any audience!",
  "What's Hermione's favorite magical sport? 'Hermione'-racquetball!",
  "Why did Hermione become a magical inventor? She always thought 'Hermione'-side the box!",
  "What do you call it when Hermione is studying magical history? 'Hermione'-ology!",
  "Why did Hermione start a magical photography studio? She captured 'Hermione'-orable moments!",
  "What's Hermione's favorite magical dessert? 'Hermione'-clair!",
  "Why did Hermione become a magical mentor? She loved 'Hermione'-spiring others!",
  "What do you call it when Hermione is at a magical party? 'Hermione'-mingling with the guests!",
  "Why did Hermione start a magical cooking show? She was a 'Hermione'-ster chef!",
  "What's Hermione's favorite magical animal? 'Hermione'-ger!",
  "Why did Hermione become a magical architect? She knew how to 'Hermione'-sign magical buildings!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "Why was the math book sad? It had too many problems.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the coffee file a police report? It got mugged.",
  "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the coffee file a police report? It got mugged.",
  "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
  "Why was the math book sad? It had too many problems.",
  "Why did the bicycle fall over? It was two-tired.",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the coffee file a police report? It got mugged.",
  "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
  "Why was the math book sad? It had too many problems.",
  "Why did the bicycle fall over? It was two-tired.",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the coffee file a police report? It got mugged.",
  "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
  "Why was the math book sad? It had too many problems.",
  "Why did the bicycle fall over? It was two-tired.",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the coffee file a police report? It got mugged.",
  "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
  "Why was the math book sad? It had too many problems.",
  "Why did the bicycle fall over? It was two-tired.",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the coffee file a police report? It got mugged.",
  "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
  "Why was the math book sad? It had too many problems.",
  "Why did the bicycle fall over? It was two-tired.",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the coffee file a police report? It got mugged.",
  "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
  "Why was the math book sad? It had too many problems.",
  "Why did the bicycle fall over? It was two-tired.",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the coffee file a police report? It got mugged.",
  "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
  "Why was the math book sad? It had too many problems.",
  "Why did the bicycle fall over? It was two-tired.",

  "Why did Harry Potter refuse to go to the Quidditch game? He was 'spell'-bound by Hermione.",
  "Why did Hermione break up with Ron? He kept 'wand'-ering off in the wrong direction.",
  "Why did Harry Potter and Hermione go to the Room of Requirement? They needed some 'private' study time.",
  "Why did Hermione enjoy Transfiguration class? She liked the idea of 'changing' things up.",
  "Why did the Sorting Hat recommend Hermione for Gryffindor? She had the courage to follow her 'desires'.",
  "Why did Harry Potter and Hermione prefer Defense Against the Dark Arts class? They were 'attracted' to the subject.",
  "Why did Hermione excel at Potions class? She knew the right 'mixtures' to use.",
  "Why did Harry Potter and Hermione visit the Forbidden Forest? They wanted to explore each other's 'wild' side.",
  "Why did Hermione become a magical researcher? She loved discovering 'hidden' knowledge.",
  "Why did Harry Potter and Hermione stay up late in the Gryffindor common room? They were having a 'magical' time together.",
  "Why did Hermione become a Prefect? She knew how to 'manage' responsibilities.",
  "Why did Harry Potter and Hermione enjoy Divination class? They were curious about their 'future' together.",
  "Why did Hermione become a Patronus expert? She wanted to protect what she 'cherished' the most.",
  "Why did Harry Potter and Hermione love the Great Hall feasts? They had a passion for 'indulging' in delicious food.",
  "Why did Hermione enjoy Ancient Runes class? She appreciated the 'mysterious' symbols and meanings.",
  "Why did Harry Potter and Hermione make a great team in the Triwizard Tournament? They had 'unwavering' trust in each other.",
  "Why did Hermione start a magical law club? She had a 'just' sense of right and wrong.",
  "Why did Harry Potter and Hermione sneak into the restricted section of the library? They wanted to explore 'forbidden' knowledge.",
  "Why did Hermione excel at Charms class? She knew how to cast a 'seductive' charm.",
  "Why did Harry Potter and Hermione visit Hogsmeade together? They loved the 'intimate' atmosphere.",
  "Why did Hermione become an Animagus? She wanted to experience the world from a 'different' perspective.",
  "Why did Harry Potter and Hermione enjoy Astronomy class? They loved 'stargazing' together.",
  "Why did Hermione become a magical healer? She had a 'gentle' touch when caring for others.",
  "Why did Harry Potter and Hermione join the Slug Club? They wanted to network and 'socialize' with influential wizards.",
  "Why did Hermione excel at Transfiguration class? She could 'transform' her ideas into reality.",
  "Why did Harry Potter and Hermione attend the Yule Ball together? They wanted to 'showcase' their dancing skills.",
  "Why did Hermione start a magical debate club? She loved engaging in 'stimulating' discussions.",
  "Why did Harry Potter and Hermione prefer the Room of Requirement? It provided the perfect 'setting' for their needs.",
  "Why did Hermione excel at Ancient Studies? She had a 'deep' fascination with history.",
  "Why did Harry Potter and Hermione go to the Black Lake? They enjoyed the 'serenity' of the water.",
  "Why did Hermione become a magical researcher? She loved 'exploring' new topics.",
  "Why did Harry Potter and Hermione enjoy Herbology class? They liked getting their hands 'dirty' in the greenhouse.",
  "Why did Hermione become a Charms expert? She knew how to create 'enchanting' moments.",
  "Why did Harry Potter and Hermione visit the Room of Requirement together? They had a 'special' secret spot.",
  "Why did Hermione become a magical counselor? She was good at 'listening' and providing support.",
  "Why did Harry Potter and Hermione enjoy Care of Magical Creatures? They loved 'bonding' with the animals.",
  "Why did Hermione excel at Arithmancy? She had a 'logical' approach to magical numbers.",
  "Why did Harry Potter and Hermione love flying on broomsticks? It gave them a 'thrilling' sense of freedom.",
  "Why did Hermione start a magical art class? She enjoyed expressing herself through 'creative' mediums.",
  "Why did Harry Potter and Hermione appreciate the Room of Requirement? It allowed them to have 'private' moments.",
  "Why did Hermione become an expert in magical plants? She was fascinated by their 'potent' properties.",
  "Why did Harry Potter and Hermione enjoy magical dueling? It gave them a sense of 'adrenaline' and challenge.",
  "Why did Hermione excel at Arithmancy? She enjoyed the 'intricate' patterns and calculations.",
  "Why did Harry Potter and Hermione love visiting Diagon Alley? It was a place for 'sensory' exploration.",
  "Why did Hermione become a magical historian? She loved 'revisiting' the past.",
  "Why did Harry Potter and Hermione enjoy the Hogwarts Express ride? It was a 'romantic' journey.",
  "Why did Hermione start a magical literature club? She appreciated 'complex' and thought-provoking stories.",
  "Why did Harry Potter and Hermione enjoy exploring the Forbidden Forest? It was full of 'hidden' wonders.",
  "Why did Hermione excel at Defense Against the Dark Arts? She knew how to protect herself from 'danger'.",
  "Why did Harry Potter and Hermione spend hours in the library? They valued 'intellectual' stimulation.",
  "Why did Hermione become a magical archeologist? She loved 'unearthing' ancient artifacts.",
  "Why did Harry Potter and Hermione enjoy the Astronomy Tower? It provided a 'breathtaking' view of the stars.",
  "Why did Hermione excel at Potions class? She had a 'meticulous' attention to detail.",
  "Why did Harry Potter and Hermione enjoy the Room of Requirement? It allowed them to 'unwind' together.",
  "Why did Hermione become a magical linguist? She loved 'decoding' ancient languages.",
  "Why did Harry Potter and Hermione enjoy visiting the Room of Requirement? It was a 'secretive' escape.",
  "Why did Hermione excel at Transfiguration class? She knew how to 'morph' her ideas into reality.",
  "Why did Harry Potter and Hermione love Care of Magical Creatures? They enjoyed 'bonding' with the animals.",
  "Why did Hermione become an expert in magical plants? She was fascinated by their 'potent' properties.",
  "Why did Harry Potter and Hermione enjoy flying on broomsticks? It gave them a 'thrilling' sense of freedom.",
  "Why did Hermione start a magical art class? She enjoyed expressing herself through 'creative' mediums.",
  "Why did Harry Potter and Hermione appreciate the Room of Requirement? It allowed them to have 'private' moments.",
  "Why did Hermione become a magical historian? She loved 'revisiting' the past.",
  "Why did the lonely Indian engineering student become a software engineer? To find 'code'-mpanionship.",
  "Why did the lonely Indian engineering student create a chatbot? To have someone to 'talk' to.",
  "Why did the lonely Indian engineering student start programming? To 'connect' with the virtual world.",
  "Why did the lonely Indian engineering student join an online forum? To find 'like'-minded individuals.",
  "Why did the lonely Indian engineering student take up photography? To 'capture' fleeting moments of joy.",
  "Why did the lonely Indian engineering student start playing online games? To be part of a 'virtual' community.",
  "Why did the lonely Indian engineering student start a YouTube channel? To share thoughts with 'subscribers'.",
  "Why did the lonely Indian engineering student become a food blogger? To 'taste' a sense of belonging.",
  "Why did the lonely Indian engineering student start writing a blog? To find 'express'-ions for emotions.",
  "Why did the lonely Indian engineering student start a podcast? To have a 'voice' in the digital world.",
  "Why did the lonely Indian engineering student learn to play the guitar? To 'strum'-ble upon happiness.",
  "Why did the lonely Indian engineering student become a freelancer? To find work and 'earn' some friends.",
  "Why did the lonely Indian engineering student become a travel enthusiast? To find solace in 'exploring' new places.",
  "Why did the lonely Indian engineering student adopt a pet? To have a 'furry' companion at home.",
  "Why did the lonely Indian engineering student take up painting? To 'brush' away feelings of isolation.",
  "Why did the lonely Indian engineering student start volunteering? To 'connect' with the community.",
  "Why did the lonely Indian engineering student learn to cook? To find comfort in 'savor'-ing self-made meals.",
  "Why did the lonely Indian engineering student start a book club? To 'immerse' in different worlds.",
  "Why did the lonely Indian engineering student become a fitness enthusiast? To find 'strength' in body and mind.",
  "Why did the lonely Indian engineering student take up gardening? To find joy in 'growing' something beautiful.",
  "Why did the lonely Indian engineering student join a social media group? To find 'virtual' companionship.",
  "Why did the lonely Indian engineering student become a mentor? To share knowledge and 'guide' others.",
  "Why did the lonely Indian engineering student start learning a new language? To 'connect' with diverse cultures.",
  "Why did the lonely Indian engineering student become a poetry enthusiast? To find solace in 'verses'.",
  "Why did the lonely Indian engineering student take up dancing? To 'express' emotions through movements.",
  "Why did the lonely Indian engineering student start meditating? To find 'inner' peace and calmness.",
  "Why did the lonely Indian engineering student start bird-watching? To 'admire' the beauty of nature.",
  "Why did the lonely Indian engineering student become a social activist? To find 'purpose' in helping others.",
  "Why did the lonely Indian engineering student start coding competitions? To 'challenge' themselves and make friends.",
  "Why did the lonely Indian engineering student take up astronomy? To 'explore' the mysteries of the universe.",
  "Why did the lonely Indian engineering student start learning to cook regional dishes? To 'savor' their heritage.",
  "Why did the lonely Indian engineering student become a film enthusiast? To find 'emotions' in cinematic stories.",
  "Why did the lonely Indian engineering student start a blog on mental health? To 'share' struggles and support others.",
  "Why did the lonely Indian engineering student join a dance class? To 'embrace' the rhythm of life.",
  "Why did the lonely Indian engineering student take up calligraphy? To find 'artistic' beauty in written words.",
  "Why did the lonely Indian engineering student start doing DIY projects? To 'create' their own happiness.",
  "Why did the lonely Indian engineering student become a fitness trainer? To 'motivate' others and find connections.",
  "Why did the lonely Indian engineering student start playing chess online? To 'challenge' minds and make friends.",
  "Why did the lonely Indian engineering student start learning photography? To 'capture' moments of joy.",
  "Why did the lonely Indian engineering student join a hiking group? To 'explore' nature and find companionship.",
  "Why did the lonely Indian engineering student start writing short stories? To 'narrate' their feelings.",
  "Why did the lonely Indian engineering student become a tech blogger? To 'share' knowledge and connect.",
  "Why did the lonely Indian engineering student start learning to play the piano? To find 'harmony' within.",
  "Why did the lonely Indian engineering student take up running? To 'stride' towards new friendships.",
  "Why did the lonely Indian engineering student start practicing yoga? To find 'inner' peace and serenity.",
  "Why did the lonely Indian engineering student become a podcast host? To 'engage' with listeners worldwide.",
  "Why did the lonely Indian engineering student join a charity organization? To 'give' back and find purpose.",
  "Why did the lonely Indian engineering student start learning magic tricks? To 'amaze' and entertain others.",
  "Why did the lonely Indian engineering student become a history buff? To 'immerse' in the past and find connection.",
  "Why did the lonely Indian engineering student take up pottery? To 'mold' their emotions into art.",
  "Why did the lonely Indian engineering student start learning martial arts? To 'defend' against loneliness.",
  "Why did the lonely Indian engineering student become a documentary filmmaker? To 'share' real-life stories.",
  "Why did the lonely Indian engineering student join a debate club? To 'articulate' thoughts and find camaraderie.",
  "Why did the lonely Indian engineering student start learning graphic design? To 'express' creativity.",
  "Why did the lonely Indian engineering student become a part of a theater group? To 'act' out their emotions.",
  "Why did the lonely Indian engineering student join a language exchange program? To 'connect' globally.",
  "Why did the lonely Indian engineering student start learning origami? To 'fold' beauty from solitude.",
  "Why did the lonely Indian engineering student become a motivational speaker? To 'inspire' and find purpose.",
  "Why did the lonely Indian engineering student take up surfing? To 'ride' the waves of loneliness.",
  "Why did the lonely Indian engineering student start a podcast on mental health? To 'share' struggles and support others.",
  "Why did the lonely Indian engineering student join a dance class? To 'embrace' the rhythm of life.",
  "Why did the lonely Indian engineering student take up calligraphy? To find 'artistic' beauty in written words.",
  "Why did the lonely Indian engineering student start doing DIY projects? To 'create' their own happiness.",
  "Why did the lonely Indian engineering student become a fitness trainer? To 'motivate' others and find connections.",
  "Engineer: My routine is simple,Everyday I wake up and suffer.",
  "My professor said that the exam is 'open-book.' I was hoping it meant 'open your laptop and find the answers online.'",
  "Why did the engineering student always carry a pencil? To 'graph' every aspect of their life.",
  "Why did the engineering student stay up all night? They thought it was a 'design' requirement.",
  "Why did the engineering student bring a ruler to bed? To 'measure' how much sleep they are losing.",
  "I told my friend I'm getting enough sleep in college. They laughed and said, 'Yeah, 8 hours per week.'",
  "What's an engineering student's favorite meal? 'RAM'en noodles.",
  "Why did the engineering student have a photo of a clock in their wallet? To remember 'time' management.",
  "Why did the engineering student always carry an umbrella? To 'shield' themselves from overwhelming projects.",
  "Why did the engineering student love computer programming? Because they found 'bugs' more interesting than social ones.",
  "Why did the engineering student start a garden? To 'cultivate' patience and watch it grow... like their assignments.",
  "Why did the engineering student become a stand-up comedian? To laugh at their own 'debugging' jokes.",
  "What's an engineering student's favorite type of music? 'Heavy' metal.",
  "Why did the engineering student start playing chess? To master the art of 'strategic' procrastination.",
  "Why did the engineering student always carry a tape measure? To 'measure' the distance between deadlines.",
  "Why did the engineering student love geometry class? It was the only time they could 'tri' and relax.",
  "Why did the engineering student start a blog? To share their 'wiring' thoughts with the world.",
  "Why did the engineering student become a marathon runner? To practice for the 'endless' exams.",
  "Why did the engineering student have a map of the library on their bedroom wall? To navigate the 'maze' of books.",
  "Why did the engineering student always carry a compass? To find their way out of 'circuits' of confusion.",
  "Why did the engineering student love physics class? They found the 'momentum' of chaos fascinating.",
  "Why did the engineering student start an online business? To 'bridge' the gap between assignments and funds.",
  "Why did the engineering student take up painting? To 'express' their emotions in abstract ways.",
  "Why did the engineering student love rainy days? It was the perfect excuse to 'interface' with their computer.",
  "Why did the engineering student start a podcast? To have a platform for 'vocalizing' their academic struggles.",
  "Why did the engineering student become a mathematician? To calculate the 'probability' of getting enough sleep.",
  "Why did the engineering student start a YouTube channel? To 'broadcast' their daily struggles.",
  "Why did the engineering student have a screenshot of their exam grades on their phone? To remind them of their 'errors.'",
  "Why did the engineering student start playing the guitar? To 'strum' away stress and anxiety.",
  "Why did the engineering student join a meditation class? To find 'inner peace' amidst the chaos of exams.",
  "Why did the engineering student always carry a stress ball? To 'squeeze' away their worries.",
  "Why did the engineering student take up photography? To 'capture' moments of triumph and defeat.",
  "Why did the engineering student love coffee? Because it's the 'fuel' that keeps them running.",
  "Why did the engineering student always carry a notebook? To 'sketch' out solutions to their problems.",
  "Why did the engineering student join a dance class? To 'move' away the monotony of their routine.",
  "Why did the engineering student become a tutor? To 'teach' themselves by teaching others.",
  "Why did the engineering student start reading self-help books? To 'debug' their mindset.",
  "Why did the engineering student start a support group? To 'connect' with others facing the same struggles.",
  "Why did the engineering student join a laughter club? To 'laugh' away their worries, even if it's forced.",
  "Why did the engineering student take up running? To 'run' away from their problems (literally).",
  "Why did the engineering student have a poster of a clock in their room? To remind them of the 'ticking' deadlines.",
  "Why did the engineering student start learning magic tricks? To 'disappear' from their responsibilities.",
  "Why did the engineering student take up cooking? To 'stir' up some excitement in their routine.",
  "Why did the engineering student join a hiking club? To 'explore' new paths and challenges.",
  "Why did the engineering student always carry a stress-relief toy? To 'squeeze' out the tension.",
  "Why did the engineering student start a blog? To share their 'circuits' of thoughts with the world.",
  "Why did the engineering student love music? Because it's the 'key signature' to their sanity.",
  "Why did the engineering student join a swimming class? To 'dive' into a different world and relax.",
  "Why did the engineering student start a podcast on mental health? To 'speak out' about their struggles.",
  "Why did the engineering student start gardening? To find 'growth' amidst academic stagnation.",
  "Why did the engineering student always carry a planner? To 'schedule' their moments of despair.",
  "Why did the engineering student join a yoga class? To find 'balance' amidst the chaos.",
  "Why did the engineering student take up photography? To 'capture' moments of triumph and defeat.",
  "Why did the engineering student love coffee? Because it's the 'fuel' that keeps them running.",
  "Why did the engineering student always carry a notebook? To 'sketch' out solutions to their problems.",
  "Why did the engineering student join a dance class? To 'move' away the monotony of their routine.",
  "Why did the engineering student become a tutor? To 'teach' themselves by teaching others.",
  "Why did the engineering student start reading self-help books? To 'debug' their mindset.",
  "Why did the engineering student start a support group? To 'connect' with others facing the same struggles.",
  "Why did the engineering student join a laughter club? To 'laugh' away their worries, even if it's forced.",
  "Why did the engineering student take up running? To 'run' away from their problems (literally).",
  "Why did the engineering student have a poster of a clock in their room? To remind them of the 'ticking' deadlines.",
  "Why did the engineering student start learning magic tricks? To 'disappear' from their responsibilities.",
  "Why did the engineering student take up cooking? To 'stir' up some excitement in their routine.",
  "Why did the engineering student join a hiking club? To 'explore' new paths and challenges.",
];
function shuffleArray(array: any[]) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method === "GET") {
    return GET(req, res);
  } else {
    res.status(405).send("Method not allowed");
  }
}

async function GET(req: NextApiRequest, res: NextApiResponse) {
  const { jokeType } = req.query;

  const joke =
    shuffleArray(harryPotterJokes)[
      Math.floor(Math.random() * harryPotterJokes.length)
    ];
  return res.status(200).json(joke);
}
